FROM python:3.12-slim

RUN pip install duckdb && apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY duckdb_server.py /app/
COPY data /app/data

EXPOSE 8080
CMD ["python", "duckdb_server.py"]
